spring:
  application:
    name: StockDividend

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:h2:mem:StockDividend;DB_CLOSE_DELAY=1
    username: sa
    password:
    driverClassName: org.h2.Driver

  data:
    redis:
      port: 6379
      host: localhost

  jwt:
    secret: ZGF5b25lLXNwcmluZy1ib290LWRpdmlkZW5kLXByb2plY3QtdHV0b3JpYWwtand0LXNlY3JldAo=

scheduler:
  scrap:
    yahoo: "0 0 0 * * *"